name: Auto-merge main → master

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  create-and-enable-automerge:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main at workflow commit
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: Create a sync branch from main
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b sync/main-to-master-${{ github.run_id }}
          git push --set-upstream origin sync/main-to-master-${{ github.run_id }}

      - name: Create PR main → master from sync branch
        id: create-pr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: sync changes from main to master"
          branch: sync/main-to-master-${{ github.run_id }}
          base: master
          title: "Sync main → master"
          body: "Automated sync of changes from main after successful CI."

      - name: Enable auto-merge for the PR
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ steps.create-pr.outputs.pull-request-number }}
          merge-method: squash
